user:
  name:
    max_lenght: 50
  email:
    max_lenght: 250
  password:
    min_lenght: 6
  show:
    per_page: 5
sessions:
  remember: "1"
album:
  name:
    max_length: 140
  caption:
    max_length: 200
post_comment:
  max_content:  140
